global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'Desmos-Node-A-Metrics'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'desmos-node-a:8080' ]
        labels:
          application: 'desmos-blockchain-connector'

  - job_name: 'Desmos-Node-B-Metrics'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'desmos-node-b:8080' ]
        labels:
          application: 'desmos-blockchain-connector'