version: '3.8'

networks:
  desmos:
    name: desmos-network
    driver: bridge

services:

  # INFRASTRUCTURE
  ganache:
    image: trufflesuite/ganache-cli:latest
    command:
      - "-l"
      - "800000"
      - "--account"
      - '0x041de193683f117a4b0f0b94f8e3e98d9dcf233010a538c6662c41a18188e038,100000000000000000000'
      - "--account"
      - '0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f,100000000000000000000'
      - "--account"
      - '0x09bac90daf84adc6ca0e3161e3a67c80e4a2ab79d7f55bf9b82f566e6d62ad87,100000000000000000000'
    ports:
      - "8545:8545"
    networks:
      - desmos

  contract-create:
    image: quay.io/digitelts/dome-contract-deploy:1.0.0
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      NODE_ENDPOINT: http://ganache:8545/
      T_NET_CHAIN_ID: 83584648538
      B_NET_CHAIN_ID: 2020
    restart: on-failure
    depends_on:
      - ganache
    networks:
      - desmos

  # ACCESS NODE A

  init-desmos:
    image: alpine
    command: [ "/bin/sh", "-c", "chmod 777 scripts/init-script.sh && scripts/init-script.sh scorpio-node-a 9090 dlt-adapter-node-a 8080 postgres-node-a 5432 scorpio-node-b 9090 dlt-adapter-node-b 8080 postgres-node-b 5432" ]
    volumes:
      - ./examples/access-node/scripts/init-script.sh:/scripts/init-script.sh
    restart: "no"
    networks:
      - desmos

  scorpio-node-a:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgis-node-a
    ports:
      - "9090:9090"
    links:
      - postgis-node-a
    networks:
      - desmos

  postgis-node-a:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    networks:
      - desmos

  desmos-node-a:
    image: desmos-api
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-node-a:5432/dbtest
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-node-a:5432/dbtest
      LOGGING_LEVEL_ES_IN2_DESMOS: DEBUG
      OPERATOR_ORGANIZATION_IDENTIFIER: VATES-S0000000E
      DLT_ADAPTER_PROVIDER: digitelts
      DLT_ADAPTER_INTERNAL_DOMAIN: http://dlt-adapter-node-a:8080
      DLT_ADAPTER_EXTERNAL_DOMAIN: http://dlt-adapter-node-a:8080
      TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-a:8080/api/v1/notifications/dlt
      TX_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
      BROKER_PROVIDER: scorpio
      BROKER_INTERNAL_DOMAIN: http://scorpio-node-a:9090
      BROKER_EXTERNAL_DOMAIN: http://scorpio-node-a:9090
      NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-a:8080/api/v1/notifications/broker
      NGSI_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
    ports:
      - "9092:8080"
    depends_on:
      init-desmos:
        condition: service_completed_successfully
    networks:
      - desmos

  postgres-node-a:
    image: postgres:16.1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest
    networks:
      - desmos

  dlt-adapter-node-a:
    image: quay.io/digitelts/dlt-adapter:1.4.1
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      DOME_EVENTS_CONTRACT_ADDRESS: 0x37532a3dbf29942d10fb8ba57dc35d2134fe494d
      RPC_ADDRESS: http://ganache:8545
      DOME_PRODUCTION_BLOCK_NUMBER: 0
      ISS: 0x8723da6199704b971030dc1838c443ffa9c67f27788ab4a92bce20ecd4c6402e #VATES-S0000000E
    ports:
      - "9094:8080"
    networks:
      - desmos

  # ACCESS NODE B

  scorpio-node-b:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgis-node-b
    ports:
      - "9091:9090"
    depends_on:
      - postgis-node-b
    networks:
      - desmos

  postgis-node-b:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    networks:
      - desmos

  desmos-node-b:
    image: in2workspace/desmos-api:v0.6.0-SNAPSHOT
    #image: desmos-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-node-b:5432/dbtest
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-node-b:5432/dbtest
      LOGGING_LEVEL_ES_IN2_DESMOS: DEBUG
      OPERATOR_ORGANIZATION_IDENTIFIER: VATES-S9999999E
      DLT_ADAPTER_PROVIDER: digitelts
      DLT_ADAPTER_INTERNAL_DOMAIN: http://dlt-adapter-node-b:8080
      DLT_ADAPTER_EXTERNAL_DOMAIN: http://dlt-adapter-node-b:8080
      TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-b:8080/api/v1/notifications/dlt
      TX_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
      BROKER_PROVIDER: scorpio
      BROKER_INTERNAL_DOMAIN: http://scorpio-node-b:9090
      BROKER_EXTERNAL_DOMAIN: http://scorpio-node-b:9090
      NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-b:8080/api/v1/notifications/broker
      NGSI_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
    ports:
      - "9093:8080"
    depends_on:
      init-desmos:
        condition: service_completed_successfully
    networks:
      - desmos

  postgres-node-b:
    image: postgres:16.1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest
    networks:
      - desmos

  dlt-adapter-node-b:
    image: quay.io/digitelts/dlt-adapter:1.4.1
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      DOME_EVENTS_CONTRACT_ADDRESS: 0x37532a3dbf29942d10fb8ba57dc35d2134fe494d
      RPC_ADDRESS: http://ganache:8545
      DOME_PRODUCTION_BLOCK_NUMBER: 0
      ISS: 0x40b0ab9dfd960064fb7e9fdf77f889c71569e349055ff563e8d699d8fa97fa90 #VATES-S9999999E
    ports:
      - "9095:8080"
    networks:
      - desmos